PRODUCTS = {'GALAXY_SOUNDS_BLACK_HOLES': {'last_ts_value': 999900,
                               'log_flush_ts': 1000,
                               'maker_size': 3,
                               'position_limit': 10,
                               'strategy': 'naive_tight_mm',
                               'tighten_ticks': 1,
                               'ts_increment': 100},
 'GALAXY_SOUNDS_DARK_MATTER': {'last_ts_value': 999900,
                               'log_flush_ts': 1000,
                               'maker_size': 5,
                               'position_limit': 10,
                               'strategy': 'naive_tight_mm',
                               'tighten_ticks': 1,
                               'ts_increment': 100},
 'GALAXY_SOUNDS_PLANETARY_RINGS': {'last_ts_value': 999900,
                                   'log_flush_ts': 1000,
                                   'maker_size': 3,
                                   'position_limit': 10,
                                   'strategy': 'naive_tight_mm',
                                   'tighten_ticks': 1,
                                   'ts_increment': 100},
 'GALAXY_SOUNDS_SOLAR_FLAMES': {'last_ts_value': 999900,
                                'log_flush_ts': 1000,
                                'maker_size': 3,
                                'position_limit': 5,
                                'strategy': 'naive_tight_mm',
                                'tighten_ticks': 1,
                                'ts_increment': 100},
 'GALAXY_SOUNDS_SOLAR_WINDS': {'last_ts_value': 999900,
                               'log_flush_ts': 1000,
                               'maker_size': 3,
                               'position_limit': 10,
                               'strategy': 'naive_tight_mm',
                               'tighten_ticks': 1,
                               'ts_increment': 100},
 'MICROCHIP_CIRCLE': {'last_ts_value': 999900,
                      'log_flush_ts': 1000,
                      'maker_size': 3,
                      'position_limit': 10,
                      'strategy': 'naive_tight_mm',
                      'tighten_ticks': 1,
                      'ts_increment': 100},
 'MICROCHIP_OVAL': {'last_ts_value': 999900,
                    'log_flush_ts': 1000,
                    'maker_size': 5,
                    'position_limit': 10,
                    'strategy': 'naive_tight_mm',
                    'tighten_ticks': 1,
                    'ts_increment': 100},
 'MICROCHIP_RECTANGLE': {'entry_z': 1.2,
                         'exit_z': 0.0,
                         'last_ts_value': 999900,
                         'mean_half_life': 5000,
                         'partner_product': 'MICROCHIP_SQUARE',
                         'passive_size': 3,
                         'position_limit': 10,
                         'strategy': 'coint_mm_v1',
                         'taker_size': 10,
                         'tighten_ticks': 1,
                         'z_window': 1000},
 'MICROCHIP_SQUARE': {'ema_half_life': 100,
                      'exit_threshold': 80,
                      'last_ts_value': 999900,
                      'log_flush_ts': 1000,
                      'position_limit': 10,
                      'strategy': 'trend_follow_v2',
                      'threshold': 250,
                      'ts_increment': 100,
                      'warmup_ticks': 0},
 'MICROCHIP_TRIANGLE': {'last_ts_value': 999900,
                        'log_flush_ts': 1000,
                        'maker_size': 3,
                        'position_limit': 10,
                        'strategy': 'naive_tight_mm',
                        'tighten_ticks': 1,
                        'ts_increment': 100},
 'OXYGEN_SHAKE_CHOCOLATE': {'last_ts_value': 999900,
                            'log_flush_ts': 1000,
                            'maker_size': 5,
                            'position_limit': 10,
                            'strategy': 'naive_tight_mm',
                            'tighten_ticks': 1,
                            'ts_increment': 100},
 'OXYGEN_SHAKE_EVENING_BREATH': {'last_ts_value': 999900,
                                 'log_flush_ts': 1000,
                                 'maker_size': 5,
                                 'position_limit': 10,
                                 'strategy': 'naive_tight_mm',
                                 'tighten_ticks': 1,
                                 'ts_increment': 100},
 'OXYGEN_SHAKE_GARLIC': {'ema_half_life': 150,
                         'exit_threshold': 150,
                         'last_ts_value': 999900,
                         'log_flush_ts': 1000,
                         'position_limit': 10,
                         'strategy': 'trend_follow_v2',
                         'threshold': 700,
                         'ts_increment': 100,
                         'warmup_ticks': 0},
 'OXYGEN_SHAKE_MINT': {'last_ts_value': 999900,
                       'log_flush_ts': 1000,
                       'maker_size': 3,
                       'position_limit': 10,
                       'strategy': 'naive_tight_mm',
                       'tighten_ticks': 1,
                       'ts_increment': 100},
 'OXYGEN_SHAKE_MORNING_BREATH': {'last_ts_value': 999900,
                                 'log_flush_ts': 1000,
                                 'maker_size': 5,
                                 'position_limit': 10,
                                 'strategy': 'naive_tight_mm',
                                 'tighten_ticks': 1,
                                 'ts_increment': 100},
 'PANEL_1X2': {'ema_half_life': 100,
               'exit_threshold': 30,
               'last_ts_value': 999900,
               'log_flush_ts': 1000,
               'position_limit': 10,
               'strategy': 'trend_follow_v2',
               'threshold': 80,
               'ts_increment': 100,
               'warmup_ticks': 0},
 'PANEL_1X4': {'last_ts_value': 999900,
               'log_flush_ts': 1000,
               'maker_size': 5,
               'position_limit': 10,
               'strategy': 'naive_tight_mm',
               'tighten_ticks': 1,
               'ts_increment': 100},
 'PANEL_2X2': {'last_ts_value': 999900,
               'log_flush_ts': 1000,
               'maker_size': 3,
               'position_limit': 10,
               'strategy': 'naive_tight_mm',
               'tighten_ticks': 1,
               'ts_increment': 100},
 'PANEL_2X4': {'last_ts_value': 999900,
               'log_flush_ts': 1000,
               'maker_size': 5,
               'position_limit': 10,
               'strategy': 'naive_tight_mm',
               'tighten_ticks': 1,
               'ts_increment': 100},
 'PANEL_4X4': {'last_ts_value': 999900,
               'log_flush_ts': 1000,
               'maker_size': 3,
               'position_limit': 5,
               'strategy': 'naive_tight_mm',
               'tighten_ticks': 1,
               'ts_increment': 100},
 'PEBBLES_L': {'last_ts_value': 999900,
               'log_flush_ts': 1000,
               'maker_size': 3,
               'position_limit': 5,
               'strategy': 'naive_tight_mm',
               'tighten_ticks': 1,
               'ts_increment': 100},
 'PEBBLES_S': {'last_ts_value': 999900,
               'log_flush_ts': 1000,
               'maker_size': 3,
               'position_limit': 10,
               'strategy': 'naive_tight_mm',
               'tighten_ticks': 1,
               'ts_increment': 100},
 'PEBBLES_XL': {'edge_ticks': 7.0,
                'ewma_alpha': 0.05,
                'last_ts_value': 999900,
                'partner_products': ['PEBBLES_L', 'PEBBLES_M', 'PEBBLES_S', 'PEBBLES_XS'],
                'passive_half_spread': 6.0,
                'passive_size': 5,
                'position_limit': 10,
                'strategy': 'pebbles_arb_v1',
                'sum_target': 50000.0,
                'taker_size': 10},
 'PEBBLES_XS': {'ema_half_life': 150,
                'exit_threshold': 80,
                'last_ts_value': 999900,
                'log_flush_ts': 1000,
                'position_limit': 10,
                'strategy': 'trend_follow_v2',
                'threshold': 250,
                'ts_increment': 100,
                'warmup_ticks': 0},
 'ROBOT_DISHES': {'entry_threshold': 20.0,
                  'exit_ticks': 0,
                  'last_ts_value': 999900,
                  'passive_size': 0,
                  'position_limit': 10,
                  'strategy': 'ar1_mean_rev_v1',
                  'taker_size': 10},
 'ROBOT_IRONING': {'ema_half_life': 150,
                   'exit_threshold': 40,
                   'last_ts_value': 999900,
                   'log_flush_ts': 1000,
                   'position_limit': 10,
                   'strategy': 'trend_follow_v2',
                   'threshold': 100,
                   'ts_increment': 100,
                   'warmup_ticks': 0},
 'ROBOT_LAUNDRY': {'entry_z': 1.5,
                   'exit_z': 0.0,
                   'last_ts_value': 999900,
                   'mean_half_life': 5000,
                   'partner_product': 'ROBOT_VACUUMING',
                   'passive_size': 1,
                   'position_limit': 10,
                   'strategy': 'coint_mm_v1',
                   'taker_size': 10,
                   'tighten_ticks': 1,
                   'z_window': 2000},
 'ROBOT_MOPPING': {'ema_half_life': 150,
                   'exit_threshold': 40,
                   'last_ts_value': 999900,
                   'log_flush_ts': 1000,
                   'position_limit': 10,
                   'strategy': 'trend_follow_v2',
                   'threshold': 100,
                   'ts_increment': 100,
                   'warmup_ticks': 0},
 'ROBOT_VACUUMING': {'entry_z': 1.5,
                     'exit_z': 0.0,
                     'last_ts_value': 999900,
                     'mean_half_life': 5000,
                     'partner_product': 'ROBOT_LAUNDRY',
                     'passive_size': 3,
                     'position_limit': 10,
                     'strategy': 'coint_mm_v1',
                     'taker_size': 10,
                     'tighten_ticks': 1,
                     'z_window': 2000},
 'SLEEP_POD_COTTON': {'ema_half_life': 100,
                      'exit_threshold': 30,
                      'last_ts_value': 999900,
                      'log_flush_ts': 1000,
                      'position_limit': 10,
                      'strategy': 'trend_follow_v2',
                      'threshold': 80,
                      'ts_increment': 100,
                      'warmup_ticks': 0},
 'SLEEP_POD_NYLON': {'ema_half_life': 100,
                     'exit_threshold': 30,
                     'last_ts_value': 999900,
                     'log_flush_ts': 1000,
                     'position_limit': 10,
                     'strategy': 'trend_follow_v2',
                     'threshold': 80,
                     'ts_increment': 100,
                     'warmup_ticks': 0},
 'SLEEP_POD_POLYESTER': {'ema_half_life': 150,
                         'exit_threshold': 150,
                         'last_ts_value': 999900,
                         'log_flush_ts': 1000,
                         'position_limit': 10,
                         'strategy': 'trend_follow_v2',
                         'threshold': 600,
                         'ts_increment': 100,
                         'warmup_ticks': 0},
 'SLEEP_POD_SUEDE': {'last_ts_value': 999900,
                     'log_flush_ts': 1000,
                     'maker_size': 3,
                     'position_limit': 10,
                     'strategy': 'naive_tight_mm',
                     'tighten_ticks': 1,
                     'ts_increment': 100},
 'SNACKPACK_CHOCOLATE': {'last_ts_value': 999900,
                         'log_flush_ts': 1000,
                         'maker_size': 5,
                         'position_limit': 10,
                         'strategy': 'naive_tight_mm',
                         'tighten_ticks': 1,
                         'ts_increment': 100},
 'SNACKPACK_PISTACHIO': {'last_ts_value': 999900,
                         'log_flush_ts': 1000,
                         'maker_size': 5,
                         'position_limit': 10,
                         'strategy': 'naive_tight_mm',
                         'tighten_ticks': 1,
                         'ts_increment': 100},
 'SNACKPACK_RASPBERRY': {'last_ts_value': 999900,
                         'log_flush_ts': 1000,
                         'maker_size': 5,
                         'position_limit': 10,
                         'strategy': 'naive_tight_mm',
                         'tighten_ticks': 1,
                         'ts_increment': 100},
 'SNACKPACK_STRAWBERRY': {'last_ts_value': 999900,
                          'log_flush_ts': 1000,
                          'maker_size': 5,
                          'position_limit': 10,
                          'strategy': 'naive_tight_mm',
                          'tighten_ticks': 1,
                          'ts_increment': 100},
 'SNACKPACK_VANILLA': {'last_ts_value': 999900,
                       'log_flush_ts': 1000,
                       'maker_size': 5,
                       'position_limit': 10,
                       'strategy': 'naive_tight_mm',
                       'tighten_ticks': 1,
                       'ts_increment': 100},
 'TRANSLATOR_ASTRO_BLACK': {'last_ts_value': 999900,
                            'log_flush_ts': 1000,
                            'maker_size': 3,
                            'position_limit': 10,
                            'strategy': 'naive_tight_mm',
                            'tighten_ticks': 1,
                            'ts_increment': 100},
 'TRANSLATOR_ECLIPSE_CHARCOAL': {'last_ts_value': 999900,
                                 'log_flush_ts': 1000,
                                 'maker_size': 3,
                                 'position_limit': 10,
                                 'strategy': 'naive_tight_mm',
                                 'tighten_ticks': 1,
                                 'ts_increment': 100},
 'TRANSLATOR_GRAPHITE_MIST': {'last_ts_value': 999900,
                              'log_flush_ts': 1000,
                              'maker_size': 3,
                              'position_limit': 5,
                              'strategy': 'naive_tight_mm',
                              'tighten_ticks': 1,
                              'ts_increment': 100},
 'TRANSLATOR_VOID_BLUE': {'last_ts_value': 999900,
                          'log_flush_ts': 1000,
                          'maker_size': 5,
                          'position_limit': 10,
                          'strategy': 'naive_tight_mm',
                          'tighten_ticks': 1,
                          'ts_increment': 100},
 'UV_VISOR_AMBER': {'ema_half_life': 100,
                    'exit_threshold': 30,
                    'last_ts_value': 999900,
                    'log_flush_ts': 1000,
                    'position_limit': 10,
                    'strategy': 'trend_follow_v2',
                    'threshold': 80,
                    'ts_increment': 100,
                    'warmup_ticks': 0},
 'UV_VISOR_MAGENTA': {'last_ts_value': 999900,
                      'log_flush_ts': 1000,
                      'maker_size': 3,
                      'position_limit': 5,
                      'strategy': 'naive_tight_mm',
                      'tighten_ticks': 1,
                      'ts_increment': 100},
 'UV_VISOR_ORANGE': {'last_ts_value': 999900,
                     'log_flush_ts': 1000,
                     'maker_size': 5,
                     'position_limit': 10,
                     'strategy': 'naive_tight_mm',
                     'tighten_ticks': 1,
                     'ts_increment': 100},
 'UV_VISOR_RED': {'last_ts_value': 999900,
                  'log_flush_ts': 1000,
                  'maker_size': 5,
                  'position_limit': 10,
                  'strategy': 'naive_tight_mm',
                  'tighten_ticks': 1,
                  'ts_increment': 100},
 'UV_VISOR_YELLOW': {'ema_half_life': 100,
                     'exit_threshold': 150,
                     'last_ts_value': 999900,
                     'log_flush_ts': 1000,
                     'position_limit': 10,
                     'strategy': 'trend_follow_v2',
                     'threshold': 700,
                     'ts_increment': 100,
                     'warmup_ticks': 0}}
