"""Product configuration and round-level strategy registry.

Each product maps to a strategy name + params dict.  The Trader dispatcher
uses this to instantiate the right BaseStrategy subclass per product.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Any, Dict


@dataclass(frozen=True)
class ProductConfig:
    """Everything needed to instantiate and configure a strategy for one product."""
    symbol: str
    strategy: str                          # key into STRATEGY_REGISTRY
    position_limit: int = 20
    params: Dict[str, Any] = field(default_factory=dict)


# ── Round 0 ──────────────────────────────────────────────────────────
ROUND_0: Dict[str, ProductConfig] = {
    "EMERALDS": ProductConfig(
        symbol="EMERALDS",
        strategy="market_maker",
        position_limit=80,
        params=dict(
            anchor_price=10000.0,
            fair_mode="anchored_microprice",
            anchor_weight=0.92,
            ema_alpha=0.08,
            take_edge=1.0,
            quote_half_spread=2,
            inventory_aversion=1.2,
            max_inventory_bias_ticks=4,
            maker_size=16,
            join_best=True,
            improve_ticks=1,
        ),
    ),
    "TOMATOES": ProductConfig(
        symbol="TOMATOES",
        strategy="market_maker",
        position_limit=80,
        params=dict(
            anchor_price=None,
            fair_mode="microprice_ema",
            anchor_weight=0.0,
            ema_alpha=0.18,
            take_edge=1.0,
            quote_half_spread=2,
            inventory_aversion=1.5,
            max_inventory_bias_ticks=5,
            maker_size=14,
            join_best=True,
            improve_ticks=1,
        ),
    ),
}

# ── Round templates (filled in when products are revealed) ───────────
# These are EXAMPLES showing how future rounds will be configured.
# Update them as soon as the round opens and products are disclosed.

ROUND_1: Dict[str, ProductConfig] = {
    "ASH_COATED_OSMIUM": ProductConfig(
        symbol="ASH_COATED_OSMIUM",
        strategy="naive_tight_mm",
        position_limit=80,
        params=dict(
            maker_size=20,
            tighten_ticks=1,
            log_flush_ts=1000,
            ts_increment=100,
            last_ts_value=999900,
        ),
    ),
    "INTARIAN_PEPPER_ROOT": ProductConfig(
        symbol="INTARIAN_PEPPER_ROOT",
        strategy="naive_tight_mm",
        position_limit=80,
        params=dict(
            maker_size=20,
            tighten_ticks=1,
            log_flush_ts=1000,
            ts_increment=100,
            last_ts_value=999900,
        ),
    ),
}

ROUND_2: Dict[str, ProductConfig] = {}
ROUND_3: Dict[str, ProductConfig] = {}
ROUND_4: Dict[str, ProductConfig] = {}
ROUND_5: Dict[str, ProductConfig] = {}


ROUNDS: Dict[int, Dict[str, ProductConfig]] = {
    0: ROUND_0,
    1: ROUND_1,
    2: ROUND_2,
    3: ROUND_3,
    4: ROUND_4,
    5: ROUND_5,
}


# ── Per-member overrides (for experimentation) ──────────────────────

def _override(base: ProductConfig, **kwargs) -> ProductConfig:
    """Return a copy of base with params updated."""
    new_params = {**base.params, **kwargs}
    return ProductConfig(
        symbol=base.symbol,
        strategy=kwargs.pop("strategy", base.strategy) if "strategy" in kwargs else base.strategy,
        position_limit=kwargs.pop("position_limit", base.position_limit) if "position_limit" in kwargs else base.position_limit,
        params=new_params,
    )


MEMBER_OVERRIDES: Dict[str, Dict[int, Dict[str, ProductConfig]]] = {
    "champion": {},   # uses base configs as-is
    "leo": {
        0: {
            "EMERALDS": _override(ROUND_0["EMERALDS"], quote_half_spread=2, maker_size=18, inventory_aversion=1.0),
            "TOMATOES": _override(ROUND_0["TOMATOES"], ema_alpha=0.14, take_edge=0.75, maker_size=12, inventory_aversion=1.2),
        },
    },
    "tibo_AvSt": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="avellaneda_stoikov",
                gamma=0.001,
                kappa=.8,
                maker_size_base_pct=0.5, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.15, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # mid_smooth_window=0 => disabled
                mid_smooth_half_life=25,
                sigma_window=200,
                sigma_floor=0.5,
                sigma_half_life=60,

                ts_increment=100,
                last_ts_value=199900,       # IMC live: last timestamp of the day
                bt_last_ts_value=999900,    # internal backtest data: last timestamp of the day
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="avellaneda_stoikov",
                gamma=0.05, # grid searched
                kappa=2.0,  # grid searched
                maker_size_base_pct=0.3, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.25, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # grid searched # mid_smooth_window=0 => disabled
                mid_smooth_half_life=8, # grid searched -> could be between 5 and 15
                sigma_window=150, # grid searched
                sigma_floor=0.5,
                sigma_half_life=50, # grid searched

                ts_increment=100,
                last_ts_value=199900,
                bt_last_ts_value=199900,
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
        },
    },
    "leo_naive": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm",
                maker_size=18,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm",
                maker_size=10,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
        },
    },
    "leo_naive_v1_max": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm",
                maker_size=999,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm",
                maker_size=999,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
        },
    },
    "leo_naive_v2": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v2",
                maker_size=18,
                tighten_ticks=1,
                max_tighten_ticks=4,
                decay_interval=3,
                inv_skew_ticks=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v2",
                maker_size=10,
                tighten_ticks=1,
                max_tighten_ticks=4,
                decay_interval=3,
                inv_skew_ticks=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v3": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v3",
                front_size=5,
                tighten_ticks=1,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v3",
                front_size=5,
                tighten_ticks=1,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v4": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v4",
                tighten_ticks=1,
                inv_skew_ticks=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v4",
                tighten_ticks=1,
                inv_skew_ticks=4,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v5": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v5",
                tighten_ticks=1,
                inv_skew_ticks=0,
                spread_extra_threshold=0,
                size_reduce_ratio=1.0,
                imb_threshold=0.2,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v5",
                tighten_ticks=1,
                inv_skew_ticks=4,
                spread_extra_threshold=0,
                size_reduce_ratio=1.0,
                imb_threshold=0.0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v6": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v6",
                tighten_ticks=1,
                take_edge=1.0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v6",
                tighten_ticks=1,
                take_edge=1.0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v7": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v7",
                tighten_ticks=1,
                take_edge=1.0,
                asym_strength=0.0,
                spread_min_frac=1.0,
                flow_window=0,
                cooldown_ticks=0,
                pj_detect=0,
                pj_size_frac=1.0,
                pj_qty_threshold=0,
                qty_join_threshold=5,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v7",
                tighten_ticks=1,
                take_edge=1.0,
                asym_strength=0.0,
                spread_min_frac=1.0,
                flow_window=0,
                cooldown_ticks=0,
                pj_detect=0,
                pj_size_frac=1.0,
                pj_qty_threshold=0,
                qty_join_threshold=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v8": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v8",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                log_flush_ts=0,
                total_ticks=10000000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v8",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.55,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                log_flush_ts=0,
                total_ticks=10000000,
            ),
        },
    },
    "leo_round1_naive": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm",
                maker_size=80,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm",
                maker_size=80,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "theo": {
        0: {
            "EMERALDS": _override(ROUND_0["EMERALDS"], take_edge=0.5, quote_half_spread=1, maker_size=14, inventory_aversion=1.6),
            "TOMATOES": _override(ROUND_0["TOMATOES"], ema_alpha=0.22, take_edge=0.5, quote_half_spread=1, maker_size=16, inventory_aversion=1.8, max_inventory_bias_ticks=6),
        },
    },
    "theo_round1": {
        1: {
            # ASH_COATED_OSMIUM: mean-reverting, pure V9 (trend disabled = V8 behaviour)
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v9",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                # trend disabled
                trend_alpha=0.0,
                log_flush_ts=0,
                total_ticks=10000000,
            ),
            # INTARIAN_PEPPER_ROOT: strong uptrend, V9 trend-following enabled
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v9",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                # trend-following: slow EMA, target long ~30 units in strong uptrend
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.3,
                log_flush_ts=0,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v10": {
        1: {
            # ASH_COATED_OSMIUM: oscillates ~10000 → mean-reversion signal
            # Buys aggressively when below 10000, sells when above
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                # mean-reversion: anchor at 10000
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,      # 10-tick deviation → shift 4 ticks
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,  # target ±30 units at max shift
                trend_take_boost=0.2,       # modest aggression at extremes
                trend_jump_threshold=1.0,
                log_flush_ts=10000,         # flush every 10k ts → visible in live logs
                total_ticks=10000000,
            ),
            # INTARIAN_PEPPER_ROOT: strong uptrend, V10 trend + fixed jump filter
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                # trend-following: slightly more aggressive than V9
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,        # was 5.0
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,       # was 0.3
                trend_jump_threshold=1.5,   # suppress jump filter when trend > 1.5 ticks
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v11": {
        1: {
            # ASH unchanged from V10 for now: user is iterating only on IPR.
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            # IPR V11: keep V10 trend logic but stop passive ask churn when we
            # are already very long in a strong uptrend.
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v11",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v12": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v12",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                trend_buy_uptick_block_threshold=3.0,
                trend_buy_uptick_min_position_frac=0.10,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v13": {
        1: {
            # ASH stays on the V10 mean-reversion setup while we iterate on IPR.
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            # V13 = V11 hold logic + tuned entry aggression from realistic sweeps.
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v11",
                maker_size=80,
                tighten_ticks=1,
                take_edge=0.75,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.55,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v14a": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v14",
                maker_size=24,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_position_frac=0.90,
                trend_hold_sell_size_frac=0.35,
                trend_sell_patience=0.30,
                target_mode="time_only",
                schedule_total_ticks=100000,
                schedule_t1_frac=0.25,
                schedule_t2_frac=0.70,
                schedule_t3_frac=0.90,
                schedule_early_target_frac=1.00,
                schedule_mid_target_frac=0.75,
                schedule_late_target_frac=0.35,
                schedule_end_target_frac=0.05,
                max_take_buy_size=16,
                max_take_sell_size=12,
                fast_alpha=0.20,
                dip_window=25,
                dip_trend_threshold=99.0,
                dip_min_pullback=99.0,
                dip_take_boost=0.0,
                dip_buy_size_boost=0.0,
                chase_max_extension=99.0,
                chase_buy_edge_penalty=0.0,
                chase_buy_size_frac=1.0,
                buy_size_boost_when_under=0.60,
                sell_size_frac_when_under=0.0,
                sell_size_boost_when_over=0.75,
                buy_size_frac_when_over=0.35,
                bid_skew_ticks_when_under=0.0,
                ask_skew_ticks_when_under=2.5,
                bid_retreat_ticks_when_over=1.0,
                ask_unwind_ticks_when_over=1.5,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v14b": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v14",
                maker_size=22,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_position_frac=0.90,
                trend_hold_sell_size_frac=0.30,
                trend_sell_patience=0.35,
                target_mode="time_only",
                schedule_total_ticks=100000,
                schedule_t1_frac=0.25,
                schedule_t2_frac=0.70,
                schedule_t3_frac=0.90,
                schedule_early_target_frac=1.00,
                schedule_mid_target_frac=0.75,
                schedule_late_target_frac=0.35,
                schedule_end_target_frac=0.05,
                max_take_buy_size=12,
                max_take_sell_size=10,
                fast_alpha=0.22,
                dip_window=30,
                dip_trend_threshold=2.0,
                dip_min_pullback=1.5,
                dip_take_boost=0.8,
                dip_buy_size_boost=0.35,
                chase_max_extension=2.5,
                chase_buy_edge_penalty=1.0,
                chase_buy_size_frac=0.25,
                buy_size_boost_when_under=0.60,
                sell_size_frac_when_under=0.0,
                sell_size_boost_when_over=0.75,
                buy_size_frac_when_over=0.35,
                bid_skew_ticks_when_under=0.0,
                ask_skew_ticks_when_under=2.5,
                bid_retreat_ticks_when_over=1.0,
                ask_unwind_ticks_when_over=1.5,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v14c": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v14",
                maker_size=24,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_position_frac=0.80,
                trend_hold_sell_size_frac=0.45,
                trend_sell_patience=0.45,
                target_mode="trend_plus_floor",
                schedule_total_ticks=100000,
                schedule_t1_frac=0.25,
                schedule_t2_frac=0.70,
                schedule_t3_frac=0.90,
                schedule_early_target_frac=0.45,
                schedule_mid_target_frac=0.30,
                schedule_late_target_frac=0.15,
                schedule_end_target_frac=0.05,
                max_take_buy_size=10,
                max_take_sell_size=12,
                fast_alpha=0.20,
                dip_window=25,
                dip_trend_threshold=99.0,
                dip_min_pullback=99.0,
                dip_take_boost=0.0,
                dip_buy_size_boost=0.0,
                chase_max_extension=99.0,
                chase_buy_edge_penalty=0.0,
                chase_buy_size_frac=1.0,
                buy_size_boost_when_under=0.45,
                sell_size_frac_when_under=0.25,
                sell_size_boost_when_over=0.70,
                buy_size_frac_when_over=0.50,
                bid_skew_ticks_when_under=1.0,
                ask_skew_ticks_when_under=2.0,
                bid_retreat_ticks_when_over=1.0,
                ask_unwind_ticks_when_over=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v14d": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v14",
                maker_size=22,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_position_frac=0.80,
                trend_hold_sell_size_frac=0.35,
                trend_sell_patience=0.45,
                target_mode="trend_plus_floor",
                schedule_total_ticks=100000,
                schedule_t1_frac=0.25,
                schedule_t2_frac=0.70,
                schedule_t3_frac=0.90,
                schedule_early_target_frac=0.55,
                schedule_mid_target_frac=0.35,
                schedule_late_target_frac=0.15,
                schedule_end_target_frac=0.05,
                max_take_buy_size=12,
                max_take_sell_size=12,
                fast_alpha=0.22,
                dip_window=30,
                dip_trend_threshold=2.0,
                dip_min_pullback=1.5,
                dip_take_boost=0.7,
                dip_buy_size_boost=0.30,
                chase_max_extension=2.5,
                chase_buy_edge_penalty=1.0,
                chase_buy_size_frac=0.35,
                buy_size_boost_when_under=0.45,
                sell_size_frac_when_under=0.15,
                sell_size_boost_when_over=0.75,
                buy_size_frac_when_over=0.50,
                bid_skew_ticks_when_under=1.0,
                ask_skew_ticks_when_under=2.0,
                bid_retreat_ticks_when_over=1.0,
                ask_unwind_ticks_when_over=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v15": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v15",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.95,
                trend_hold_sell_size_frac=0.10,
                trend_hold_ask_extra_ticks=2,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v16": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            # V16: keep V11 hold logic, but improve IPR entry timing with
            # "buy dips / don't chase" instead of broad inventory cycling.
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v16",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                fast_alpha=0.22,
                dip_window=30,
                dip_trend_threshold=2.0,
                dip_min_pullback=4.0,
                dip_take_boost=0.35,
                dip_buy_size_boost=0.15,
                chase_max_extension=1.5,
                chase_take_edge_penalty=0.75,
                chase_take_size_frac=0.50,
                max_take_buy_size=6,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v17": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v17",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                fast_alpha=0.22,
                dip_window=30,
                dip_trend_threshold=2.0,
                dip_min_pullback=4.0,
                dip_take_boost=0.35,
                dip_buy_size_boost=0.15,
                chase_max_extension=1.5,
                chase_take_edge_penalty=0.75,
                chase_take_size_frac=0.50,
                max_take_buy_size=6,
                core_position_frac=0.80,
                rebuy_block_buy_size_frac=0.15,
                rebuy_block_take_cap_frac=0.0,
                rebuy_block_extension_threshold=0.5,
                trim_trend_threshold=4.0,
                trim_extension_threshold=1.0,
                trim_sell_size=6,
                trim_ask_improve_ticks=1,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "pietro": {
        0: {
            "EMERALDS": _override(ROUND_0["EMERALDS"], quote_half_spread=3, maker_size=12),
            "TOMATOES": _override(ROUND_0["TOMATOES"], ema_alpha=0.10, take_edge=1.5, quote_half_spread=3, maker_size=10, inventory_aversion=1.0),
        },
    },
    # ── Round 1 V19 — Book-Following Trend MM (THE FIX) ────────────────
    # Key fix: ask = min(FV + ask_spread_bull, best_ask) → always inside market
    # V18 bug was ask_spread_bull=9 put ask ABOVE best_ask → 0 sells
    "theo_round1_v19": {
        1: {
            # ASH_COATED_OSMIUM: unchanged V10 mean-reversion
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            # INTARIAN_PEPPER_ROOT: V19 — book-following, always inside market
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="book_following_trend_mm_v19",
                maker_size=80,
                # Fair value EWM
                fv_alpha=0.05,
                # Slope window
                slope_window=20,
                # Enter bull when FV rises 1 tick over 20 ticks
                bull_threshold=1.0,
                # Bull bid: max(FV-1, best_bid) → inside spread, leading queue
                bid_spread_bull=1.0,
                # Bull ask: min(FV+7, best_ask) → AT or inside best_ask (THE FIX)
                ask_spread_bull=7.0,
                # Neutral quotes: symmetric ±3 ticks from FV
                neut_spread=3.0,
                # Takes: modest buying above FV in bull (-2 = take up to FV+2)
                take_buy_edge_bull=-2.0,
                # Only take-sell if bid exceeds FV+12 (very conservative in bull)
                take_sell_edge_bull=12.0,
                # Neutral takes: conservative ±2
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                # Aggressive unwind in neutral when long
                unwind_take_edge=8.0,
                # Inventory
                target_bull=50,
                inventory_soft_ratio=0.40,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.40,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    # ── Round 1 V20 — V19 + explicit sell-opportunity trims ───────────────
    "theo_round1_v20": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="book_following_trend_mm_v20",
                maker_size=12,
                maker_buy_size=10,
                maker_sell_size=6,
                fv_alpha=0.05,
                slope_window=20,
                bull_threshold=1.0,
                bid_spread_bull=1.0,
                ask_spread_bull=7.0,
                neut_spread=3.0,
                take_buy_edge_bull=-2.0,
                take_sell_edge_bull=12.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                unwind_min_position=20,
                target_bull=50,
                inventory_soft_ratio=0.40,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.40,
                sell_opp_edge=1.0,
                sell_opp_min_position=60,
                sell_opp_take_size=4,
                sell_opp_quote_offset=1,
                sell_opp_cooldown_ticks=6,
                rebuy_block_min_position=60,
                rebuy_block_extension=1.0,
                rebuy_block_take_cap=0,
                rebuy_block_quote_frac=0.25,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    # ── Round 1 V21 — Conservative V19 sell-opportunity trims ────────────
    "theo_round1_v21": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="book_following_trend_mm_v21",
                maker_size=80,
                fv_alpha=0.05,
                slope_window=20,
                bull_threshold=1.0,
                bid_spread_bull=1.0,
                ask_spread_bull=7.0,
                neut_spread=3.0,
                take_buy_edge_bull=-2.0,
                take_sell_edge_bull=12.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                unwind_min_position=20,
                target_bull=50,
                inventory_soft_ratio=0.40,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.40,
                opp_sell_edge=1.0,
                opp_sell_min_position=65,
                opp_sell_take_size=2,
                opp_sell_cooldown_ticks=10,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    # ── Round 1 V22 — V21 tuned to trim only at full inventory ───────────
    "theo_round1_v22": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="book_following_trend_mm_v21",
                maker_size=80,
                fv_alpha=0.05,
                slope_window=20,
                bull_threshold=1.0,
                bid_spread_bull=1.0,
                ask_spread_bull=7.0,
                neut_spread=3.0,
                take_buy_edge_bull=-2.0,
                take_sell_edge_bull=12.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                unwind_min_position=20,
                target_bull=50,
                inventory_soft_ratio=0.40,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.40,
                opp_sell_edge=1.0,
                opp_sell_min_position=80,
                opp_sell_take_size=2,
                opp_sell_cooldown_ticks=10,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v23": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v23",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                fast_alpha=0.22,
                dip_window=30,
                dip_trend_threshold=2.0,
                dip_min_pullback=4.0,
                dip_take_boost=0.35,
                dip_buy_size_boost=0.15,
                chase_max_extension=1.5,
                chase_take_edge_penalty=0.75,
                chase_take_size_frac=0.50,
                max_take_buy_size=6,
                core_position_frac=0.80,
                rebuy_block_buy_size_frac=0.15,
                rebuy_block_take_cap_frac=0.0,
                rebuy_block_extension_threshold=0.5,
                trim_trend_threshold=4.0,
                trim_extension_threshold=1.0,
                trim_sell_size=6,
                trim_ask_improve_ticks=1,
                carry_floor_trend_threshold=4.0,
                carry_floor_position_frac=0.875,
                carry_fill_take_boost=0.35,
                carry_fill_buy_size_boost=0.20,
                carry_fill_take_cap=8,
                carry_trim_start_frac=0.90,
                carry_trim_signal_edge=1.0,
                carry_trim_size=2,
                carry_trim_cooldown_ticks=8,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v24": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v24",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                fast_alpha=0.22,
                dip_window=30,
                dip_trend_threshold=2.0,
                dip_min_pullback=4.0,
                dip_take_boost=0.35,
                dip_buy_size_boost=0.15,
                chase_max_extension=1.5,
                chase_take_edge_penalty=0.75,
                chase_take_size_frac=0.50,
                max_take_buy_size=6,
                core_position_frac=0.80,
                rebuy_block_buy_size_frac=0.15,
                rebuy_block_take_cap_frac=0.0,
                rebuy_block_extension_threshold=0.5,
                rebuy_block_position_floor=80,
                trim_trend_threshold=4.0,
                trim_extension_threshold=1.0,
                trim_sell_size=4,
                trim_ask_improve_ticks=1,
                trim_floor_position=75,
                trim_signal_edge=1.0,
                trim_cooldown_ticks=8,
                accum_band_trend_threshold=4.0,
                accum_mid_start_position=60,
                accum_top_start_position=75,
                accum_mid_take_boost=0.25,
                accum_mid_buy_size_boost=0.25,
                accum_mid_take_cap=8,
                accum_top_take_boost=0.10,
                accum_top_buy_size_boost=0.10,
                accum_top_take_cap=8,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    # ── Round 1 V18 — Trend-Biased MM ──────────────────────────────────
    "theo_round1_v18": {
        1: {
            # ASH_COATED_OSMIUM: keep V10 mean-reversion (working fine)
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            # INTARIAN_PEPPER_ROOT: V18 trend-biased MM, always quotes
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_biased_mm_v18",
                maker_size=80,
                # Fair value EWM
                fv_alpha=0.05,
                # Slope window: measure trend over last 20 ticks
                slope_window=20,
                # Enter bull mode when FV rose by 1 tick over last 20 ticks
                bull_threshold=1.0,
                # Bull quotes: tight bid inside spread, wide ask above market
                bid_spread_bull=1.0,    # bid = FV - 1 (top of book, inside spread)
                ask_spread_bull=9.0,    # ask = FV + 9 (above best_ask ~FV+8)
                # Neutral quotes: symmetric inside spread
                neut_spread_bid=2.0,
                neut_spread_ask=5.0,    # ask = FV + 5 (below best_ask, normal MM)
                # Takes: aggressive buying in bull, aggressive selling to unwind
                take_buy_edge_bull=-8.0,  # take asks up to FV+8 ≈ best_ask
                take_sell_edge_bull=6.0,  # only take bids above FV+6 in bull
                take_buy_edge_neut=2.0,   # conservative buying in neutral
                take_sell_edge_neut=2.0,
                unwind_take_edge=10.0,    # aggressive sell when long in neutral
                # Inventory
                target_bull=40,           # target 40 long (50% of limit=80) in bull
                inventory_soft_ratio=0.50,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
}


def get_round_config(round_num: int, member: str = "champion") -> Dict[str, ProductConfig]:
    """Build the product config for a given round + member."""
    base = dict(ROUNDS.get(round_num, {}))
    overrides = MEMBER_OVERRIDES.get(member, {}).get(round_num, {})
    base.update(overrides)
    return base
