"""Product configuration and round-level strategy registry.

Each product maps to a strategy name + params dict.  The Trader dispatcher
uses this to instantiate the right BaseStrategy subclass per product.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Any, Dict


@dataclass(frozen=True)
class ProductConfig:
    """Everything needed to instantiate and configure a strategy for one product."""
    symbol: str
    strategy: str                          # key into STRATEGY_REGISTRY
    position_limit: int = 20
    params: Dict[str, Any] = field(default_factory=dict)


# ── Round 0 ──────────────────────────────────────────────────────────
ROUND_0: Dict[str, ProductConfig] = {
    "EMERALDS": ProductConfig(
        symbol="EMERALDS",
        strategy="market_maker",
        position_limit=80,
        params=dict(
            anchor_price=10000.0,
            fair_mode="anchored_microprice",
            anchor_weight=0.92,
            ema_alpha=0.08,
            take_edge=1.0,
            quote_half_spread=2,
            inventory_aversion=1.2,
            max_inventory_bias_ticks=4,
            maker_size=16,
            join_best=True,
            improve_ticks=1,
        ),
    ),
    "TOMATOES": ProductConfig(
        symbol="TOMATOES",
        strategy="market_maker",
        position_limit=80,
        params=dict(
            anchor_price=None,
            fair_mode="microprice_ema",
            anchor_weight=0.0,
            ema_alpha=0.18,
            take_edge=1.0,
            quote_half_spread=2,
            inventory_aversion=1.5,
            max_inventory_bias_ticks=5,
            maker_size=14,
            join_best=True,
            improve_ticks=1,
        ),
    ),
}

# ── Round templates (filled in when products are revealed) ───────────
# These are EXAMPLES showing how future rounds will be configured.
# Update them as soon as the round opens and products are disclosed.

ROUND_1: Dict[str, ProductConfig] = {
    "ASH_COATED_OSMIUM": ProductConfig(
        symbol="ASH_COATED_OSMIUM",
        strategy="naive_tight_mm",
        position_limit=80,
        params=dict(
            maker_size=20,
            tighten_ticks=1,
            log_flush_ts=1000,
            ts_increment=100,
            last_ts_value=999900,
        ),
    ),
    "INTARIAN_PEPPER_ROOT": ProductConfig(
        symbol="INTARIAN_PEPPER_ROOT",
        strategy="naive_tight_mm",
        position_limit=80,
        params=dict(
            maker_size=20,
            tighten_ticks=1,
            log_flush_ts=1000,
            ts_increment=100,
            last_ts_value=999900,
        ),
    ),
}

ROUND_2: Dict[str, ProductConfig] = {}
ROUND_3: Dict[str, ProductConfig] = {}
ROUND_4: Dict[str, ProductConfig] = {}
ROUND_5: Dict[str, ProductConfig] = {}


ROUNDS: Dict[int, Dict[str, ProductConfig]] = {
    0: ROUND_0,
    1: ROUND_1,
    2: ROUND_2,
    3: ROUND_3,
    4: ROUND_4,
    5: ROUND_5,
}


# ── Per-member overrides (for experimentation) ──────────────────────

def _override(base: ProductConfig, **kwargs) -> ProductConfig:
    """Return a copy of base with params updated."""
    new_params = {**base.params, **kwargs}
    return ProductConfig(
        symbol=base.symbol,
        strategy=kwargs.pop("strategy", base.strategy) if "strategy" in kwargs else base.strategy,
        position_limit=kwargs.pop("position_limit", base.position_limit) if "position_limit" in kwargs else base.position_limit,
        params=new_params,
    )


MEMBER_OVERRIDES: Dict[str, Dict[int, Dict[str, ProductConfig | None]]] = {
    "champion": {},   # uses base configs as-is
    "leo": {
        0: {
            "EMERALDS": _override(ROUND_0["EMERALDS"], quote_half_spread=2, maker_size=18, inventory_aversion=1.0),
            "TOMATOES": _override(ROUND_0["TOMATOES"], ema_alpha=0.14, take_edge=0.75, maker_size=12, inventory_aversion=1.2),
        },
    },
    "tibo_AvSt": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="avellaneda_stoikov",
                gamma=0.001,
                kappa=.8,
                maker_size_base_pct=0.5, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.15, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # mid_smooth_window=0 => disabled
                mid_smooth_half_life=25,
                sigma_window=200,
                sigma_floor=0.5,
                sigma_half_life=60,

                ts_increment=100,
                last_ts_value=199900,       # IMC live: last timestamp of the day
                bt_last_ts_value=999900,    # internal backtest data: last timestamp of the day
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="avellaneda_stoikov",
                gamma=0.05, # grid searched
                kappa=2.0,  # grid searched
                maker_size_base_pct=0.3, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.25, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # grid searched # mid_smooth_window=0 => disabled
                mid_smooth_half_life=8, # grid searched -> could be between 5 and 15
                sigma_window=150, # grid searched
                sigma_floor=0.5,
                sigma_half_life=50, # grid searched

                ts_increment=100,
                last_ts_value=199900,
                bt_last_ts_value=199900,
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
        },
    },
    "tibo_mm": {
        1: {  "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="avellaneda_stoikov",
                gamma=0.001,
                kappa=.8,
                maker_size_base_pct=0.5, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.15, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # mid_smooth_window=0 => disabled
                mid_smooth_half_life=25,
                sigma_window=200,
                sigma_floor=0.5,
                sigma_half_life=60,

                ts_increment=100,
                last_ts_value=199900,       # IMC live: last timestamp of the day
                bt_last_ts_value=999900,    # internal backtest data: last timestamp of the day
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
             "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="avellaneda_stoikov",
                gamma=0.05, # grid searched
                kappa=2.0,  # grid searched
                maker_size_base_pct=0.3, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.25, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # grid searched # mid_smooth_window=0 => disabled
                mid_smooth_half_life=8, # grid searched -> could be between 5 and 15
                sigma_window=150, # grid searched
                sigma_floor=0.5,
                sigma_half_life=50, # grid searched

                ts_increment=100,
                last_ts_value=199900,
                bt_last_ts_value=199900,
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
        },
    },
    "tibo_naive_mm": {
        1: {  "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm",
                gamma=0.001,
                kappa=.8,
                maker_size_base_pct=0.5, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.15, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # mid_smooth_window=0 => disabled
                mid_smooth_half_life=25,
                sigma_window=200,
                sigma_floor=0.5,
                sigma_half_life=60,

                ts_increment=100,
                last_ts_value=199900,       # IMC live: last timestamp of the day
                bt_last_ts_value=999900,    # internal backtest data: last timestamp of the day
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
             "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm",
                gamma=0.05, # grid searched
                kappa=2.0,  # grid searched
                maker_size_base_pct=0.3, # in pct of position limit, scales down as inventory increases
                take_edge=2,
                pct_kept_for_takers=0.25, # capacity kept for aggressive takers
                
                min_half_spread=1.0,
                mid_smooth_window=50, # grid searched # mid_smooth_window=0 => disabled
                mid_smooth_half_life=8, # grid searched -> could be between 5 and 15
                sigma_window=150, # grid searched
                sigma_floor=0.5,
                sigma_half_life=50, # grid searched

                ts_increment=100,
                last_ts_value=199900,
                bt_last_ts_value=199900,
                log_flush_ts=1000, # fires at 900, 1900, 2900 ... every 1000 timestamp units
            ),
        },
    },
    "tibo_mm_first": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="mm_first",
                inv_step_threshold=0.9,   # step to L2 (join) when |pos| >= 80% of limit
                take_edge=1,            # take if ask <= mid_smooth - 1 (or bid >= mid_smooth + 1)
                maker_size_base_pct=0.75,  # base passive size as % of position limit

                pct_kept_for_takers=0.1,  # capacity reserved for taker orders
                mid_smooth_window=50,
                mid_smooth_half_life=10,
                taker_buy_threshold = 9990,  # classify taker buys at >= this price
                taker_sell_threshold= 10025,

                gap_trigger_min=10,           # min tick gap L1→L2 to fire gap exploit
                gap_trigger_max_vol_pct=0.2, # L1 "thin" threshold: 10% of limit (=8 units)
                gap_trigger_confirm_ticks=1,  # require 2 consecutive ticks to filter transient gaps

                ts_increment=100,
                last_ts_value=99900,
                log_flush_ts=1000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="mm_first",
                inv_step_threshold=0.8,
                take_edge=1.0,
                maker_size_base_pct=0.5,
                pct_kept_for_takers=0.2,
                mid_smooth_window=20,
                mid_smooth_half_life=10,

                gap_trigger_min=10,
                gap_trigger_max_vol_pct=0.10,
                gap_trigger_confirm_ticks=2,

                ts_increment=100,
                last_ts_value=99900,
                log_flush_ts=1000,
            ),
        },
    },
    "tibo_mm_first_v2": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="mm_first_v2",
                take_edge=.5,
                maker_size_base_pct=0.5,
                pct_kept_for_takers=0.1,
                mid_smooth_window=50,
                mid_smooth_half_life=10,
                taker_buy_threshold=9990,
                taker_sell_threshold=10025,

                zscore_window=50,
                zscore_threshold=1,
                zscore_size_scale=0.5,
                zscore_max_scale=5.0,

                gap_trigger_min=10,
                gap_trigger_max_vol_pct=0.1,
                gap_trigger_confirm_ticks=1,
                zscore_gap_gate=1.5,

                quote_trace_enabled=True,
                ts_increment=100,
                last_ts_value=99900,
                log_flush_ts=1000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="mm_first_v2",
                inv_step_threshold=0.8,
                take_edge=1.0,
                maker_size_base_pct=0.5,
                pct_kept_for_takers=0.2,
                mid_smooth_window=20,
                mid_smooth_half_life=10,
                gap_trigger_min=10,
                gap_trigger_max_vol_pct=0.10,
                gap_trigger_confirm_ticks=2,
                zscore_window=50,
                zscore_threshold=1.0,
                zscore_size_scale=0.5,
                zscore_max_scale=3.0,
                zscore_gap_gate=1.0,
                quote_trace_enabled=True,
                ts_increment=100,
                last_ts_value=99900,
                log_flush_ts=1000,
            ),
        },
    },
    "tibo_zscore": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="zscore",
                # z-score signal
                zscore_window=25,          # rolling window for mean/std
                zscore_threshold=2,       # |z| must exceed this to tilt sizes
                zscore_size_scale=0.5,      # scale per unit of excess z (1 + 0.5 * excess)
                zscore_max_scale=2.0,       # cap on the size multiplier
                # quoting
                take_edge=.5,
                maker_size_base_pct=0.5,
                pct_kept_for_takers=0.1,
                mid_smooth_window=50,
                mid_smooth_half_life=10,
                
                ts_increment=100,
                last_ts_value=99900,
                log_flush_ts=1000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="zscore",
                zscore_window=100,
                zscore_threshold=1.0,
                zscore_size_scale=0.5,
                zscore_max_scale=3.0,
                take_edge=1.0,
                maker_size_base_pct=0.5,
                pct_kept_for_takers=0.2,
                mid_smooth_window=20,
                mid_smooth_half_life=10,
                ts_increment=100,
                last_ts_value=99900,
                log_flush_ts=1000,
            ),
        },
    },
    "leo_naive": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm",
                maker_size=18,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm",
                maker_size=10,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
        },
    },
    "leo_naive_v1_max": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm",
                maker_size=999,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm",
                maker_size=999,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=199900,
            ),
        },
    },
    "leo_naive_v2": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v2",
                maker_size=18,
                tighten_ticks=1,
                max_tighten_ticks=4,
                decay_interval=3,
                inv_skew_ticks=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v2",
                maker_size=10,
                tighten_ticks=1,
                max_tighten_ticks=4,
                decay_interval=3,
                inv_skew_ticks=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v3": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v3",
                front_size=5,
                tighten_ticks=1,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v3",
                front_size=5,
                tighten_ticks=1,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v4": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v4",
                tighten_ticks=1,
                inv_skew_ticks=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v4",
                tighten_ticks=1,
                inv_skew_ticks=4,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v5": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v5",
                tighten_ticks=1,
                inv_skew_ticks=0,
                spread_extra_threshold=0,
                size_reduce_ratio=1.0,
                imb_threshold=0.2,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v5",
                tighten_ticks=1,
                inv_skew_ticks=4,
                spread_extra_threshold=0,
                size_reduce_ratio=1.0,
                imb_threshold=0.0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v6": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v6",
                tighten_ticks=1,
                take_edge=1.0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v6",
                tighten_ticks=1,
                take_edge=1.0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v7": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v7",
                tighten_ticks=1,
                take_edge=1.0,
                asym_strength=0.0,
                spread_min_frac=1.0,
                flow_window=0,
                cooldown_ticks=0,
                pj_detect=0,
                pj_size_frac=1.0,
                pj_qty_threshold=0,
                qty_join_threshold=5,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v7",
                tighten_ticks=1,
                take_edge=1.0,
                asym_strength=0.0,
                spread_min_frac=1.0,
                flow_window=0,
                cooldown_ticks=0,
                pj_detect=0,
                pj_size_frac=1.0,
                pj_qty_threshold=0,
                qty_join_threshold=0,
                log_flush_ts=1000,
                total_ticks=200000,
            ),
        },
    },
    "leo_naive_v8": {
        0: {
            "EMERALDS": _override(
                ROUND_0["EMERALDS"],
                strategy="naive_tight_mm_v8",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                log_flush_ts=0,
                total_ticks=10000000,
            ),
            "TOMATOES": _override(
                ROUND_0["TOMATOES"],
                strategy="naive_tight_mm_v8",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.55,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                log_flush_ts=0,
                total_ticks=10000000,
            ),
        },
    },
    "leo_round1_naive": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm",
                maker_size=80,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm",
                maker_size=80,
                tighten_ticks=1,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "buy_and_hold": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="buy_and_hold",
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="buy_and_hold",
            ),
        },
    },
    "leo_round1_naive_v7": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v7",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                asym_strength=0.0,
                spread_min_frac=1.0,
                flow_window=0,
                cooldown_ticks=0,
                pj_detect=0,
                pj_size_frac=1.0,
                pj_qty_threshold=0,
                qty_join_threshold=0,
                join_size_frac=1.0,
                level2_ticks=0,
                level2_frac=0.0,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v7",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                asym_strength=0.0,
                spread_min_frac=1.0,
                flow_window=0,
                cooldown_ticks=0,
                pj_detect=0,
                pj_size_frac=1.0,
                pj_qty_threshold=0,
                qty_join_threshold=0,
                join_size_frac=1.0,
                level2_ticks=0,
                level2_frac=0.0,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_round1_naive_v8": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v8",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v8",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.55,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_reg_lin_round1": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="round1_regression_top_book",
                mode="toxic_mm",
                maker_size=80,
                tighten_ticks=1,
                inventory_soft_ratio=0.55,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.25,
                toxic_filter=True,
                toxic_window=8,
                toxic_threshold=0.60,
                toxic_size_frac=0.60,
                jump_size_frac=0.50,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="round1_regression_top_book",
                mode="regression_mm",
                maker_size=80,
                tighten_ticks=1,
                inventory_soft_ratio=0.50,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.35,
                toxic_filter=False,
                reg_window=80,
                reg_min_points=40,
                reg_horizon=20,
                reg_signal_to_shift=0.50,
                reg_max_price_shift=1,
                reg_inventory_per_price=16.0,
                reg_inventory_cap=40,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_reg_lin_round1_v2": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="round1_regression_top_book",
                mode="regression_mm",
                maker_size=80,
                tighten_ticks=1,
                inventory_soft_ratio=0.50,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.35,
                toxic_filter=False,
                reg_window=80,
                reg_min_points=40,
                reg_horizon=20,
                reg_signal_to_shift=0.50,
                reg_max_price_shift=1,
                reg_inventory_per_price=16.0,
                reg_inventory_cap=40,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_reg_lin_round1_v3": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="round1_regression_mm_v3",
                maker_size=80,
                tighten_ticks=1,
                reg_window=120,
                reg_min_points=60,
                reg_horizon=25,
                reg_r2_floor=0.30,
                reg_r2_cap=0.80,
                reg_rmse_floor=1.0,
                reg_residual_reversion=0.35,
                trend_inv_per_tick=24.0,
                resid_inv_per_z=8.0,
                trend_inventory_cap=72,
                startup_target=36,
                startup_end_ts=25000,
                target_gap_scale=28.0,
                trend_buy_boost_per_tick=0.22,
                trend_sell_boost_per_tick=0.18,
                cheap_buy_boost_per_z=0.15,
                rich_sell_boost_per_z=0.15,
                aggravate_cut=0.05,
                one_sided_target_gap=26,
                strong_trend_ticks=0.75,
                cheap_residual_z=0.90,
                rich_residual_z=0.90,
                max_bid_extra_ticks=2,
                max_ask_relax_ticks=2,
                enable_selective_take=False,
                take_edge=6.0,
                max_take_size=8,
                take_only_toward_target=True,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_reg_lin_round1_v4": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="round1_regression_mm_v4",
                maker_size=80,
                tighten_ticks=1,
                fixed_slope=0.1015,
                residual_window=160,
                reg_horizon=25,
                reg_rmse_floor=1.0,
                trend_confidence_floor=0.65,
                trend_confidence_cap_rmse=4.0,
                reg_residual_reversion=0.35,
                trend_inv_per_tick=24.0,
                resid_inv_per_z=8.0,
                trend_inventory_cap=72,
                startup_target=36,
                startup_end_ts=25000,
                target_gap_scale=28.0,
                trend_buy_boost_per_tick=0.22,
                trend_sell_boost_per_tick=0.18,
                cheap_buy_boost_per_z=0.15,
                rich_sell_boost_per_z=0.15,
                aggravate_cut=0.05,
                one_sided_target_gap=26,
                strong_trend_ticks=0.75,
                cheap_residual_z=0.90,
                rich_residual_z=0.90,
                max_bid_extra_ticks=2,
                max_ask_relax_ticks=2,
                enable_selective_take=False,
                take_edge=6.0,
                max_take_size=8,
                take_only_toward_target=True,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_reg_lin_round1_v4_1": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="round1_regression_mm_v4",
                maker_size=80,
                tighten_ticks=1,
                fixed_slope=0.1015,
                freeze_after_points=1000,
                freeze_min_points=300,
                freeze_r2_min=0.80,
                residual_window=160,
                reg_horizon=25,
                reg_r2_floor=0.30,
                reg_r2_cap=0.85,
                reg_rmse_floor=1.0,
                trend_confidence_floor=0.65,
                trend_confidence_cap_rmse=4.0,
                reg_residual_reversion=0.35,
                trend_inv_per_tick=24.0,
                resid_inv_per_z=8.0,
                trend_inventory_cap=72,
                startup_target=36,
                startup_end_ts=25000,
                target_gap_scale=28.0,
                trend_buy_boost_per_tick=0.22,
                trend_sell_boost_per_tick=0.18,
                cheap_buy_boost_per_z=0.15,
                rich_sell_boost_per_z=0.15,
                aggravate_cut=0.05,
                one_sided_target_gap=26,
                strong_trend_ticks=0.75,
                cheap_residual_z=0.90,
                rich_residual_z=0.90,
                max_bid_extra_ticks=2,
                max_ask_relax_ticks=2,
                enable_selective_take=False,
                take_edge=6.0,
                max_take_size=8,
                take_only_toward_target=True,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_reg_lin_round1_v5": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="round1_regression_mm_v5",
                maker_size=80,
                tighten_ticks=1,
                seed_slope=0.1015,
                block_size=100,
                min_completed_blocks=5,
                reg_horizon=25,
                reg_r2_floor=0.85,
                reg_r2_cap=0.98,
                reg_rmse_floor=1.0,
                reg_residual_reversion=0.25,
                bootstrap_confidence=0.55,
                trend_inv_per_tick=26.0,
                resid_inv_per_z=7.0,
                trend_inventory_cap=74,
                startup_target=40,
                startup_end_ts=30000,
                target_gap_scale=26.0,
                trend_buy_boost_per_tick=0.24,
                trend_sell_boost_per_tick=0.20,
                cheap_buy_boost_per_z=0.18,
                rich_sell_boost_per_z=0.14,
                aggravate_cut=0.04,
                one_sided_target_gap=24,
                strong_trend_ticks=1.1,
                very_strong_trend_ticks=2.0,
                cheap_residual_z=0.9,
                rich_residual_z=1.0,
                max_bid_extra_ticks=2,
                max_ask_relax_ticks=2,
                enable_selective_take=False,
                take_edge=8.0,
                max_take_size=8,
                take_only_toward_target=True,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "pietro": {
        0: {
            "EMERALDS": _override(ROUND_0["EMERALDS"], quote_half_spread=3, maker_size=12),
            "TOMATOES": _override(ROUND_0["TOMATOES"], ema_alpha=0.10, take_edge=1.5, quote_half_spread=3, maker_size=10, inventory_aversion=1.0),
        },
    },
    
    "theo_round1_v34": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_mm_v34",
                maker_size=12,
                fv_alpha=0.05,
                short_alpha=0.22,
                slope_window=20,
                bull_threshold=1.0,
                trend_weight=0.55,
                stretch_weight=0.75,
                trim_reference_slope_weight=0.15,
                entry_reference_slope_weight=0.18,
                target_bull_base=64,
                target_bull_min=56,
                target_bull_max=78,
                target_bull_per_tick=2.0,
                startup_ticks=15000,
                startup_target=78,
                dip_target=80,
                neutral_target=0,
                warmup_no_sell_ticks=3000,
                bid_spread_bull=1.0,
                bid_spread_bull_under=0.0,
                bid_spread_neut=2.0,
                ask_spread_bull_hold=8.0,
                ask_spread_bull_trim=2.0,
                ask_spread_neut=4.0,
                bid_join_ticks=1,
                trim_ask_improve_ticks=0,
                trim_ask_local_edge=0.0,
                v18_anchor_bid_spread=1.0,
                v18_anchor_gap_ticks=1,
                v18_anchor_buy_size=2,
                take_buy_edge_bull=-6.0,
                take_buy_edge_under_boost=2.0,
                take_buy_edge_dip_boost=1.5,
                take_buy_edge_chase_penalty=2.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                max_take_buy_size=12,
                max_take_sell_size=8,
                inventory_soft_ratio=0.45,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.35,
                under_target_buy_mult=1.50,
                startup_buy_mult=1.35,
                dip_buy_mult=1.35,
                chase_buy_frac=0.60,
                hold_buy_frac=0.75,
                hold_sell_frac=0.30,
                under_target_sell_frac=0.0,
                dip_threshold=1.5,
                chase_threshold=2.5,
                trim_start_position=79,
                trim_floor_position=78,
                trim_extension_threshold=0.75,
                trim_signal_edge=1.0,
                trim_sell_size=1,
                trim_cooldown_ticks=20,
                trim_take_position=80,
                trim_take_edge=2.0,
                trim_take_stretch=1.75,
                trim_take_sell_size=1,
                rebuy_block_ticks=35,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v35": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_mm_v34",
                maker_size=12,
                fv_alpha=0.05,
                short_alpha=0.22,
                slope_window=20,
                bull_threshold=1.0,
                trend_weight=0.55,
                stretch_weight=0.75,
                trim_reference_slope_weight=0.15,
                entry_reference_slope_weight=0.18,
                target_bull_base=64,
                target_bull_min=56,
                target_bull_max=78,
                target_bull_per_tick=2.0,
                startup_ticks=15000,
                startup_target=78,
                dip_target=80,
                neutral_target=0,
                warmup_no_sell_ticks=3000,
                bid_spread_bull=1.0,
                bid_spread_bull_under=0.0,
                bid_spread_neut=2.0,
                ask_spread_bull_hold=8.0,
                ask_spread_bull_trim=2.0,
                ask_spread_neut=4.0,
                bid_join_ticks=1,
                trim_ask_improve_ticks=1,
                trim_ask_local_edge=0.0,
                v18_anchor_bid_spread=1.0,
                v18_anchor_gap_ticks=1,
                v18_anchor_buy_size=2,
                take_buy_edge_bull=-6.0,
                take_buy_edge_under_boost=2.0,
                take_buy_edge_dip_boost=1.5,
                take_buy_edge_chase_penalty=2.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                max_take_buy_size=12,
                max_take_sell_size=8,
                inventory_soft_ratio=0.45,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.35,
                under_target_buy_mult=1.50,
                startup_buy_mult=1.35,
                dip_buy_mult=1.35,
                chase_buy_frac=0.60,
                hold_buy_frac=0.75,
                hold_sell_frac=0.30,
                under_target_sell_frac=0.0,
                dip_threshold=1.5,
                chase_threshold=2.5,
                trim_start_position=79,
                trim_floor_position=78,
                trim_extension_threshold=0.75,
                trim_signal_edge=1.0,
                trim_sell_size=1,
                trim_cooldown_ticks=12,
                trim_take_position=80,
                trim_take_edge=1.5,
                trim_take_stretch=1.5,
                trim_take_sell_size=2,
                rebuy_block_ticks=35,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v36": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_mm_v34",
                maker_size=12,
                fv_alpha=0.05,
                short_alpha=0.22,
                slope_window=20,
                bull_threshold=1.0,
                trend_weight=0.55,
                stretch_weight=0.75,
                trim_reference_slope_weight=0.15,
                entry_reference_slope_weight=0.18,
                target_bull_base=64,
                target_bull_min=56,
                target_bull_max=78,
                target_bull_per_tick=2.0,
                startup_ticks=15000,
                startup_target=78,
                dip_target=80,
                neutral_target=0,
                warmup_no_sell_ticks=3000,
                bid_spread_bull=1.0,
                bid_spread_bull_under=0.0,
                bid_spread_neut=2.0,
                ask_spread_bull_hold=8.0,
                ask_spread_bull_trim=2.0,
                ask_spread_neut=4.0,
                bid_join_ticks=1,
                trim_ask_improve_ticks=0,
                trim_ask_local_edge=0.0,
                v18_anchor_bid_spread=1.0,
                v18_anchor_gap_ticks=1,
                v18_anchor_buy_size=2,
                take_buy_edge_bull=-6.0,
                take_buy_edge_under_boost=2.0,
                take_buy_edge_dip_boost=1.5,
                take_buy_edge_chase_penalty=2.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                max_take_buy_size=12,
                max_take_sell_size=8,
                inventory_soft_ratio=0.45,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.35,
                under_target_buy_mult=1.50,
                startup_buy_mult=1.35,
                dip_buy_mult=1.35,
                chase_buy_frac=0.60,
                hold_buy_frac=0.75,
                hold_sell_frac=0.30,
                under_target_sell_frac=0.0,
                dip_threshold=1.5,
                chase_threshold=2.5,
                trim_start_position=79,
                trim_floor_position=78,
                trim_extension_threshold=0.75,
                trim_signal_edge=1.0,
                trim_sell_size=1,
                trim_cooldown_ticks=20,
                trim_take_position=80,
                trim_take_edge=1.5,
                trim_take_stretch=1.5,
                trim_take_sell_size=2,
                rebuy_block_ticks=35,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v37": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_mm_v37",
                maker_size=12,
                fv_alpha=0.05,
                short_alpha=0.22,
                slope_window=20,
                bull_threshold=1.0,
                trend_weight=0.55,
                stretch_weight=0.75,
                trim_reference_slope_weight=0.15,
                entry_reference_slope_weight=0.18,
                target_bull_base=64,
                target_bull_min=56,
                target_bull_max=78,
                target_bull_per_tick=2.0,
                startup_ticks=15000,
                startup_target=78,
                startup_fast_target=52,
                startup_cold_take_cap=4,
                startup_cold_take_edge_relax=2.5,
                startup_cold_buy_frac=0.55,
                startup_cold_join_ticks=0,
                startup_cold_anchor_size=4,
                dip_target=80,
                neutral_target=0,
                warmup_no_sell_ticks=3000,
                bid_spread_bull=1.0,
                bid_spread_bull_under=0.0,
                bid_spread_neut=2.0,
                ask_spread_bull_hold=8.0,
                ask_spread_bull_trim=2.0,
                ask_spread_neut=4.0,
                bid_join_ticks=1,
                trim_ask_improve_ticks=0,
                trim_ask_local_edge=0.0,
                v18_anchor_bid_spread=1.0,
                v18_anchor_gap_ticks=1,
                v18_anchor_buy_size=2,
                take_buy_edge_bull=-6.0,
                take_buy_edge_under_boost=2.0,
                take_buy_edge_dip_boost=1.5,
                take_buy_edge_chase_penalty=2.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                max_take_buy_size=12,
                max_take_sell_size=8,
                inventory_soft_ratio=0.45,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.35,
                under_target_buy_mult=1.50,
                startup_buy_mult=1.35,
                dip_buy_mult=1.35,
                chase_buy_frac=0.60,
                hold_buy_frac=0.75,
                hold_sell_frac=0.30,
                under_target_sell_frac=0.0,
                dip_threshold=1.5,
                chase_threshold=2.5,
                trim_start_position=79,
                trim_floor_position=78,
                trim_extension_threshold=0.75,
                trim_signal_edge=1.0,
                trim_sell_size=1,
                trim_cooldown_ticks=20,
                trim_take_position=80,
                trim_take_edge=2.0,
                trim_take_stretch=1.75,
                trim_take_sell_size=1,
                rebuy_block_ticks=35,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v38": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_mm_v38",
                maker_size=12,
                fv_alpha=0.05,
                short_alpha=0.22,
                slope_window=20,
                bull_threshold=1.0,
                trend_weight=0.55,
                stretch_weight=0.75,
                trim_reference_slope_weight=0.15,
                entry_reference_slope_weight=0.18,
                target_bull_base=64,
                target_bull_min=56,
                target_bull_max=78,
                target_bull_per_tick=2.0,
                startup_ticks=15000,
                startup_target=78,
                startup_fast_target=60,
                startup_fast_take_cap=14,
                startup_cold_target=74,
                startup_cold_until=9000,
                startup_cold_take_cap=5,
                startup_cold_take_edge_relax=1.75,
                startup_cold_buy_frac=0.70,
                startup_cold_join_ticks=0,
                startup_cold_anchor_size=3,
                startup_finish_take_cap=8,
                startup_finish_take_edge_relax=0.75,
                startup_finish_buy_frac=0.90,
                startup_finish_join_ticks=1,
                startup_finish_anchor_size=3,
                dip_target=80,
                neutral_target=0,
                warmup_no_sell_ticks=3000,
                bid_spread_bull=1.0,
                bid_spread_bull_under=0.0,
                bid_spread_neut=2.0,
                ask_spread_bull_hold=8.0,
                ask_spread_bull_trim=2.0,
                ask_spread_neut=4.0,
                bid_join_ticks=1,
                trim_ask_improve_ticks=0,
                trim_ask_local_edge=0.0,
                v18_anchor_bid_spread=1.0,
                v18_anchor_gap_ticks=1,
                v18_anchor_buy_size=2,
                take_buy_edge_bull=-6.0,
                take_buy_edge_under_boost=2.0,
                take_buy_edge_dip_boost=1.5,
                take_buy_edge_chase_penalty=2.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                max_take_buy_size=12,
                max_take_sell_size=8,
                inventory_soft_ratio=0.45,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.35,
                under_target_buy_mult=1.50,
                startup_buy_mult=1.35,
                dip_buy_mult=1.35,
                chase_buy_frac=0.60,
                hold_buy_frac=0.75,
                hold_sell_frac=0.30,
                under_target_sell_frac=0.0,
                dip_threshold=1.5,
                chase_threshold=2.5,
                trim_start_position=79,
                trim_floor_position=78,
                trim_extension_threshold=0.75,
                trim_signal_edge=1.0,
                trim_sell_size=1,
                trim_cooldown_ticks=20,
                trim_take_position=80,
                trim_take_edge=1.5,
                trim_take_stretch=1.5,
                trim_take_sell_size=2,
                rebuy_block_ticks=35,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "theo_round1_v39": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_mm_v38",
                maker_size=12,
                fv_alpha=0.05,
                short_alpha=0.22,
                slope_window=20,
                bull_threshold=1.0,
                trend_weight=0.55,
                stretch_weight=0.75,
                trim_reference_slope_weight=0.15,
                entry_reference_slope_weight=0.18,
                target_bull_base=64,
                target_bull_min=56,
                target_bull_max=78,
                target_bull_per_tick=2.0,
                startup_ticks=15000,
                startup_target=78,
                startup_fast_target=60,
                startup_fast_take_cap=14,
                startup_cold_target=74,
                startup_cold_until=9000,
                startup_cold_take_cap=5,
                startup_cold_take_edge_relax=1.75,
                startup_cold_buy_frac=0.70,
                startup_cold_join_ticks=0,
                startup_cold_anchor_size=3,
                startup_finish_take_cap=8,
                startup_finish_take_edge_relax=0.75,
                startup_finish_buy_frac=0.90,
                startup_finish_join_ticks=1,
                startup_finish_anchor_size=3,
                dip_target=80,
                neutral_target=0,
                warmup_no_sell_ticks=3000,
                bid_spread_bull=1.0,
                bid_spread_bull_under=0.0,
                bid_spread_neut=2.0,
                ask_spread_bull_hold=8.0,
                ask_spread_bull_trim=2.0,
                ask_spread_neut=4.0,
                bid_join_ticks=1,
                trim_ask_improve_ticks=0,
                trim_ask_local_edge=0.0,
                v18_anchor_bid_spread=1.0,
                v18_anchor_gap_ticks=1,
                v18_anchor_buy_size=2,
                take_buy_edge_bull=-6.0,
                take_buy_edge_under_boost=2.0,
                take_buy_edge_dip_boost=1.5,
                take_buy_edge_chase_penalty=2.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                max_take_buy_size=12,
                max_take_sell_size=8,
                inventory_soft_ratio=0.45,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.35,
                under_target_buy_mult=1.50,
                startup_buy_mult=1.35,
                dip_buy_mult=1.35,
                chase_buy_frac=0.60,
                hold_buy_frac=0.75,
                hold_sell_frac=0.25,
                under_target_sell_frac=0.0,
                dip_threshold=1.5,
                chase_threshold=2.5,
                trim_start_position=79,
                trim_floor_position=78,
                trim_extension_threshold=0.75,
                trim_signal_edge=1.0,
                trim_sell_size=1,
                trim_cooldown_ticks=20,
                trim_take_position=80,
                trim_take_edge=1.5,
                trim_take_stretch=1.5,
                trim_take_sell_size=1,
                rebuy_block_ticks=35,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    # V40: same logic as V38/V39 but ultra-conservative startup to eliminate
    # the early mark-to-market PnL dip.  We minimise taker activity during
    # the first ~20k ticks so inventory is built mostly via maker fills
    # (no spread cost), which flattens the initial drawdown curve.
    "theo_round1_v40": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_mm_v38",
                maker_size=12,
                fv_alpha=0.05,
                short_alpha=0.22,
                slope_window=20,
                bull_threshold=1.0,
                trend_weight=0.55,
                stretch_weight=0.75,
                trim_reference_slope_weight=0.15,
                entry_reference_slope_weight=0.18,
                target_bull_base=64,
                target_bull_min=56,
                target_bull_max=78,
                target_bull_per_tick=2.0,
                startup_ticks=15000,
                startup_target=78,
                # Exit fast-loading very early → enter cold mode almost immediately
                startup_fast_target=15,
                startup_fast_take_cap=5,
                # Cold phase covers most of the startup window
                startup_cold_target=65,
                startup_cold_until=20000,
                startup_cold_take_cap=2,
                # Large relax → only take when ask is well below fair (≤ fair-1)
                startup_cold_take_edge_relax=7.0,
                startup_cold_buy_frac=0.45,
                startup_cold_join_ticks=1,
                startup_cold_anchor_size=2,
                startup_finish_take_cap=6,
                startup_finish_take_edge_relax=0.75,
                startup_finish_buy_frac=0.85,
                startup_finish_join_ticks=1,
                startup_finish_anchor_size=2,
                dip_target=80,
                neutral_target=0,
                # Don't sell at all for the first 8k ticks
                warmup_no_sell_ticks=8000,
                bid_spread_bull=1.0,
                # Slightly wider bid under-target to get better fill prices
                bid_spread_bull_under=1.5,
                bid_spread_neut=2.0,
                ask_spread_bull_hold=8.0,
                ask_spread_bull_trim=2.0,
                ask_spread_neut=4.0,
                bid_join_ticks=1,
                trim_ask_improve_ticks=0,
                trim_ask_local_edge=0.0,
                v18_anchor_bid_spread=1.0,
                v18_anchor_gap_ticks=1,
                v18_anchor_buy_size=2,
                take_buy_edge_bull=-6.0,
                take_buy_edge_under_boost=2.0,
                take_buy_edge_dip_boost=1.5,
                take_buy_edge_chase_penalty=2.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                max_take_buy_size=12,
                max_take_sell_size=8,
                inventory_soft_ratio=0.45,
                aggravate_min_frac=0.25,
                unwind_boost_frac=0.35,
                under_target_buy_mult=1.50,
                startup_buy_mult=1.35,
                dip_buy_mult=1.35,
                chase_buy_frac=0.60,
                hold_buy_frac=0.75,
                hold_sell_frac=0.25,
                under_target_sell_frac=0.0,
                dip_threshold=1.5,
                chase_threshold=2.5,
                trim_start_position=79,
                trim_floor_position=78,
                trim_extension_threshold=0.75,
                trim_signal_edge=1.0,
                trim_sell_size=1,
                trim_cooldown_ticks=20,
                trim_take_position=80,
                trim_take_edge=1.5,
                trim_take_stretch=1.5,
                trim_take_sell_size=1,
                rebuy_block_ticks=35,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },

    # ── Round 1 Leo fusion candidates (IPR only, ASH disabled) ──────────
    "leo_fusion_a": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="leo_fusion_a",
                maker_size=80,
                tighten_ticks=1,
                # V5 block-OLS signal
                seed_slope=0.1015,
                block_size=100,
                min_completed_blocks=5,
                reg_horizon=25,
                reg_r2_floor=0.85,
                reg_r2_cap=0.98,
                reg_rmse_floor=1.0,
                reg_residual_reversion=0.25,
                bootstrap_confidence=0.55,
                startup_target=40,
                startup_end_ts=30000,
                # V22 quoting / take / opp_sell
                bull_threshold=1.0,
                bull_min_confidence=0.4,
                target_bull=50,
                bid_spread_bull=1.0,
                ask_spread_bull=7.0,
                neut_spread=3.0,
                take_buy_edge_bull=-2.0,
                take_sell_edge_bull=12.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=8.0,
                unwind_min_position=20,
                rich_block_residual_z=0.9,
                inventory_soft_ratio=0.40,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.40,
                opp_sell_edge=1.0,
                opp_sell_min_position=80,
                opp_sell_take_size=2,
                opp_sell_cooldown_ticks=10,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_fusion_b": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="leo_fusion_b",
                maker_size=80,
                tighten_ticks=1,
                seed_slope=0.1015,
                block_size=100,
                min_completed_blocks=5,
                reg_horizon=25,
                reg_r2_floor=0.85,
                reg_r2_cap=0.98,
                reg_rmse_floor=1.0,
                reg_residual_reversion=0.25,
                bootstrap_confidence=0.55,
                # V5 inventory target params
                trend_inv_per_tick=26.0,
                resid_inv_per_z=7.0,
                trend_inventory_cap=74,
                startup_target=40,
                startup_end_ts=30000,
                target_gap_scale=26.0,
                trend_buy_boost_per_tick=0.24,
                trend_sell_boost_per_tick=0.20,
                cheap_buy_boost_per_z=0.18,
                rich_sell_boost_per_z=0.14,
                aggravate_cut=0.04,
                one_sided_target_gap=24,
                strong_trend_ticks=1.1,
                very_strong_trend_ticks=2.0,
                cheap_residual_z=0.9,
                rich_residual_z=1.0,
                max_bid_extra_ticks=2,
                max_ask_relax_ticks=2,
                # V18 quoting + take
                bull_threshold=1.0,
                bid_spread_bull=1.0,
                ask_spread_bull=9.0,
                neut_spread_bid=2.0,
                neut_spread_ask=5.0,
                take_buy_edge_bull=-8.0,
                take_sell_edge_bull=6.0,
                take_buy_edge_neut=2.0,
                take_sell_edge_neut=2.0,
                unwind_take_edge=10.0,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "leo_fusion_c": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="leo_fusion_c",
                maker_size=80,
                tighten_ticks=1,
                seed_slope=0.1015,
                block_size=100,
                min_completed_blocks=5,
                reg_horizon=25,
                reg_r2_floor=0.85,
                reg_r2_cap=0.98,
                reg_rmse_floor=1.0,
                reg_residual_reversion=0.25,
                bootstrap_confidence=0.55,
                trend_inv_per_tick=26.0,
                resid_inv_per_z=7.0,
                trend_inventory_cap=74,
                startup_target=40,
                startup_end_ts=30000,
                target_gap_scale=26.0,
                trend_buy_boost_per_tick=0.24,
                trend_sell_boost_per_tick=0.20,
                cheap_buy_boost_per_z=0.18,
                rich_sell_boost_per_z=0.14,
                aggravate_cut=0.04,
                one_sided_target_gap=24,
                strong_trend_ticks=1.1,
                very_strong_trend_ticks=2.0,
                cheap_residual_z=0.9,
                rich_residual_z=1.0,
                max_bid_extra_ticks=2,
                max_ask_relax_ticks=2,
                # Fusion C take params
                aggressive_take_edge=2.0,
                aggressive_take_size=8,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
    "theo_round1_v24": {
        1: {
            "ASH_COATED_OSMIUM": _override(
                ROUND_1["ASH_COATED_OSMIUM"],
                strategy="naive_tight_mm_v10",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="mean_rev",
                anchor_price=10000.0,
                trend_sensitivity=0.4,
                trend_max_shift=5.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.2,
                trend_jump_threshold=1.0,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="naive_tight_mm_v24",
                maker_size=80,
                tighten_ticks=1,
                take_edge=1.0,
                unwind_take_edge=0.5,
                inventory_soft_ratio=0.60,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.30,
                toxic_window=6,
                toxic_threshold=0.60,
                toxic_size_frac=0.75,
                jump_size_frac=0.50,
                signal_mode="trend",
                trend_alpha=0.005,
                trend_sensitivity=1.0,
                trend_max_shift=6.0,
                trend_inv_target_per_tick=6.0,
                trend_take_boost=0.4,
                trend_jump_threshold=1.5,
                trend_hold_threshold=4.0,
                trend_hold_min_position_frac=0.90,
                trend_hold_sell_size_frac=0.0,
                fast_alpha=0.22,
                dip_window=30,
                dip_trend_threshold=2.0,
                dip_min_pullback=4.0,
                dip_take_boost=0.35,
                dip_buy_size_boost=0.15,
                chase_max_extension=1.5,
                chase_take_edge_penalty=0.75,
                chase_take_size_frac=0.50,
                max_take_buy_size=6,
                core_position_frac=0.80,
                rebuy_block_buy_size_frac=0.15,
                rebuy_block_take_cap_frac=0.0,
                rebuy_block_extension_threshold=0.5,
                rebuy_block_position_floor=80,
                trim_trend_threshold=4.0,
                trim_extension_threshold=1.0,
                trim_sell_size=4,
                trim_ask_improve_ticks=1,
                trim_floor_position=75,
                trim_signal_edge=1.0,
                trim_cooldown_ticks=8,
                accum_band_trend_threshold=4.0,
                accum_mid_start_position=60,
                accum_top_start_position=75,
                accum_mid_take_boost=0.25,
                accum_mid_buy_size_boost=0.25,
                accum_mid_take_cap=8,
                accum_top_take_boost=0.10,
                accum_top_buy_size_boost=0.10,
                accum_top_take_cap=8,
                log_flush_ts=10000,
                total_ticks=10000000,
            ),
        },
    },
    "leo_fusion_d": {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                ROUND_1["INTARIAN_PEPPER_ROOT"],
                strategy="leo_fusion_d",
                maker_size=80,
                tighten_ticks=1,
                seed_slope=0.1015,
                block_size=100,
                min_completed_blocks=5,
                reg_horizon=25,
                reg_r2_floor=0.85,
                reg_r2_cap=0.98,
                reg_rmse_floor=1.0,
                reg_residual_reversion=0.25,
                bootstrap_confidence=0.55,
                trend_inv_per_tick=26.0,
                resid_inv_per_z=7.0,
                trend_inventory_cap=74,
                startup_target=40,
                startup_end_ts=30000,
                target_gap_scale=26.0,
                trend_buy_boost_per_tick=0.24,
                trend_sell_boost_per_tick=0.20,
                cheap_buy_boost_per_z=0.18,
                rich_sell_boost_per_z=0.14,
                aggravate_cut=0.04,
                one_sided_target_gap=24,
                strong_trend_ticks=1.1,
                very_strong_trend_ticks=2.0,
                cheap_residual_z=0.9,
                rich_residual_z=1.0,
                max_bid_extra_ticks=2,
                max_ask_relax_ticks=2,
                # Regime thresholds
                regime_confidence_floor=0.5,
                bootstrap_target_bull=40,
                # V22 shared quote params for bootstrap regime
                bid_spread_bull=1.0,
                ask_spread_bull=7.0,
                neut_spread=3.0,
                # V18 shared quote params for strong regime
                ask_spread_bull_wide=9.0,
                neut_spread_bid=2.0,
                neut_spread_ask=5.0,
                # Strong regime take
                strong_take_edge=2.0,
                strong_take_size=8,
                # Sizing
                inventory_soft_ratio=0.40,
                aggravate_min_frac=0.20,
                unwind_boost_frac=0.40,
                log_flush_ts=1000,
                ts_increment=100,
                last_ts_value=999900,
            ),
        },
    },
}


# Trend-carry window v2: same params as tibo_trend when that member exists.
if "tibo_trend" in MEMBER_OVERRIDES:
    MEMBER_OVERRIDES["tibo_trend_v2"] = {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                MEMBER_OVERRIDES["tibo_trend"][1]["INTARIAN_PEPPER_ROOT"],
                strategy="trend_carry_window_v2",
            ),
        },
    }


# ── V2 variants (block_size=200, R^2 ~0.99; rebalanced trend/residual weights
#    so residual_z can drive sells on spikes instead of being dominated by trend).
for _base in ("leo_fusion_a", "leo_fusion_b", "leo_fusion_c", "leo_fusion_d"):
    MEMBER_OVERRIDES[f"{_base}_v2"] = {
        1: {
            "ASH_COATED_OSMIUM": None,
            "INTARIAN_PEPPER_ROOT": _override(
                MEMBER_OVERRIDES[_base][1]["INTARIAN_PEPPER_ROOT"],
                block_size=200,
                trend_inv_per_tick=14.0,
                resid_inv_per_z=18.0,
            ),
        },
    }


MEMBER_OVERRIDES["leo_fusion_b_v3"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v3",
            block_size=200,
            v3_take_buy_edge=2.0,
            v3_take_sell_edge=2.0,
            v3_passive_spread=3.0,
            v3_passive_size=80,
        ),
    },
}


MEMBER_OVERRIDES["leo_fusion_b_v4"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b_v2"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v4",
            v4_regime_trend_cut=1.0,
            v4_buy_z=1.0,
            v4_sell_z=1.0,
            v4_slope_bias_k=25.0,
            v4_passive_spread=3.0,
            v4_passive_size=80,
        ),
    },
}


MEMBER_OVERRIDES["leo_fusion_b_v5"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b_v2"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v5",
            v5_core_target=80,
            v5_scalp_range=10,
            v5_scalp_edge=20.0,
            v5_scalp_spread=20.0,
            v5_accum_take_edge=0.0,
            v5_passive_size=20,
        ),
    },
}


MEMBER_OVERRIDES["leo_fusion_b_v6"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b_v2"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v6",
            v6_core_target=80,
            v6_scalp_range=10,
            v6_scalp_edge=6.0,
            v6_scalp_size=10,
        ),
    },
}


MEMBER_OVERRIDES["leo_fusion_b_v7"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b_v2"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v7",
            v7_core_target=80,
            v7_scalp_range=10,
            v7_sell_offset=15.0,
            v7_rebuy_margin=3.0,
            v7_scalp_size=5,
        ),
    },
}


MEMBER_OVERRIDES["leo_fusion_b_v8"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b_v2"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v8",
            startup_target=80,
            trend_inventory_cap=80,
            trend_inv_per_tick=18.0,
            resid_inv_per_z=12.0,
            strong_trend_ticks=0.8,
            very_strong_trend_ticks=1.5,
            max_bid_extra_ticks=3,
            take_buy_edge_bull=-10.0,
            fastfill_target=80,
            fastfill_end_ts=12000,
            fastfill_buy_edge_boost=2.0,
            fastfill_min_passive_buy=20,
        ),
    },
}


MEMBER_OVERRIDES["leo_fusion_b_v9"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b_v2"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v8",
            startup_target=80,
            trend_inventory_cap=80,
            trend_inv_per_tick=16.0,
            resid_inv_per_z=14.0,
            strong_trend_ticks=0.9,
            very_strong_trend_ticks=1.6,
            max_bid_extra_ticks=2,
            take_buy_edge_bull=-8.0,
            fastfill_target=80,
            fastfill_end_ts=12000,
            fastfill_buy_edge_boost=0.0,
            fastfill_min_passive_buy=10,
        ),
    },
}


MEMBER_OVERRIDES["leo_fusion_b_v10"] = {
    1: {
        "ASH_COATED_OSMIUM": None,
        "INTARIAN_PEPPER_ROOT": _override(
            MEMBER_OVERRIDES["leo_fusion_b_v9"][1]["INTARIAN_PEPPER_ROOT"],
            strategy="leo_fusion_b_v10",
            fastfill_deep_take_guard_end_ts=1000,
            fastfill_deep_take_max_gap_ticks=1,
        ),
    },
}


MEMBER_OVERRIDES["leo_osmium_only"] = {
    1: {
        "ASH_COATED_OSMIUM": _override(
            MEMBER_OVERRIDES["theo_round1_v24"][1]["ASH_COATED_OSMIUM"],
            strategy="osmium_mr",
            take_edge=1.75,
            tighten_ticks=1,
            unwind_take_edge=1.0,
            trend_sensitivity=0.6,
            trend_max_shift=5.0,
            trend_take_boost=0.2,
            trend_inv_target_per_tick=12.0,
            ar_gain=0.6,
            anchor_alpha=0.0,
        ),
        "INTARIAN_PEPPER_ROOT": None,
    },
}


MEMBER_OVERRIDES["champion_theo_all"] = {
    1: {
        "ASH_COATED_OSMIUM": _override(
            MEMBER_OVERRIDES["leo_osmium_only"][1]["ASH_COATED_OSMIUM"],
            strategy="osmium_mr_artifact",
        ),
        "INTARIAN_PEPPER_ROOT": MEMBER_OVERRIDES["leo_fusion_b_v10"][1]["INTARIAN_PEPPER_ROOT"],
    },
}


MEMBER_OVERRIDES["leo_osmium_v1"] = {
    1: {
        "ASH_COATED_OSMIUM": _override(
            MEMBER_OVERRIDES["theo_round1_v24"][1]["ASH_COATED_OSMIUM"],
            strategy="osmium_mr",
            take_edge=1.75,
            tighten_ticks=1,
            unwind_take_edge=1.0,
            trend_sensitivity=0.6,
            trend_max_shift=5.0,
            trend_take_boost=0.2,
            trend_inv_target_per_tick=12.0,
            ar_gain=0.6,
            anchor_alpha=0.0,
        ),
        "INTARIAN_PEPPER_ROOT": MEMBER_OVERRIDES["leo_fusion_b_v2"][1]["INTARIAN_PEPPER_ROOT"],
    },
}


MEMBER_OVERRIDES["leo_osmium_v2"] = {
    1: {
        "ASH_COATED_OSMIUM": _override(
            MEMBER_OVERRIDES["theo_round1_v24"][1]["ASH_COATED_OSMIUM"],
            strategy="osmium_mr_v2",
            take_edge=2.0,
            tighten_ticks=1,
            unwind_take_edge=1.0,
            trend_sensitivity=0.8,
            trend_max_shift=5.0,
            trend_take_boost=0.2,
            trend_inv_target_per_tick=10.0,
            ar_gain=1.2,
            anchor_alpha=0.0,
            take_abs_buy=9990,
            take_abs_sell=10025,
            gap_trigger_min=10,
            gap_trigger_max_vol_pct=0.15,
            gap_trigger_confirm_ticks=2,
        ),
        "INTARIAN_PEPPER_ROOT": None,
    },
}


def get_round_config(round_num: int, member: str = "champion") -> Dict[str, ProductConfig]:
    """Build the product config for a given round + member."""
    base = dict(ROUNDS.get(round_num, {}))
    overrides = MEMBER_OVERRIDES.get(member, {}).get(round_num, {})
    for symbol, cfg in overrides.items():
        if cfg is None:
            base.pop(symbol, None)
        else:
            base[symbol] = cfg
    return base
